# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded DIO 1.0 [list source [file join $dir packages/dio/dio.tcl]]
package ifneeded DIODisplay 1.0 [list source [file join $dir packages/dio/diodisplay.tcl]]
package ifneeded Dtcl 1.0 [list source [file join $dir packages/dtcl/dtcl.tcl]]
package ifneeded RivetTcl 1.1 [list source [file join $dir init.tcl]]
package ifneeded commserver 0.1 [list source [file join $dir packages/commserver/commserver.tcl]]
package ifneeded form 1.0 [list source [file join $dir packages/form/form.tcl]]
package ifneeded rivetparser 0.1 [list source [file join $dir packages/tclrivet/tclrivet.tcl]]
package ifneeded simpledb 0.1 [list source [file join $dir packages/simpledb/simpledb.tcl]]
package ifneeded tclrivet 0.1 [list source [file join $dir packages/tclrivet/tclrivet.tcl]]
